executable := "./exercise"

default: test

build:
  go build -o {{executable}} .

run: build
  {{executable}}

test: 
  go test

save NUM:
  cp ./main.go ./exercises/{{NUM}}.go

new:
  cp ./main.go save_bck
  cp ./template ./main.go

finish NUM:
  cp ./main.go ./exercises/{{NUM}}.go
  cp ./main.go save_bck
  cp ./template ./main.go
  cp ./template_test ./main_test.go
