executable := "./main"

build:
  go build -o {{executable}} .

run: build
  {{executable}}

save NUM:
  cp ./main.go ./exercises/{{NUM}}.go

new:
  cp ./main.go save_bck
  cp ./template ./main.go

finish NUM:
  cp ./main.go ./exercises/{{NUM}}.go
  cp ./main.go save_bck
  cp ./template ./main.go
