executable := "./main"

build:
  go build -o {{executable}} .

run: build
  {{executable}}

save NUMBER:
  cp ./main.go ./exercises/{{NUMBER}}.go

new:
  @cp ./main.go save_bck
  cp ./template ./main.go
